### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by DavidJean** [Tracecorp-Solutions/erpsystem#53]
After a system user has successfully registered and is redirected to the the dashboard, once they log out and attempt to log in again, they are first redirected to the page for entering personal information before they are redirected to the dashboard. They should be automatically redirected to the dashboard since they finalized with the registration process.

**Comment by zadokchrist** [comment]
the user us redirected because they need to complete the profile. But once the profile is complete the user will be redirected to the dashboard

**Comment by zadokchrist** [comment]
the user us redirected because they need to complete the profile. But once the profile is complete the user will be redirected to the dashboard
